// Mocks generated by Mockito 5.4.6 from annotations
// in nubank_mobile_test/test/src/ui/controllers/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nubank_mobile_test/src/core/log/log.dart' as _i3;
import 'package:nubank_mobile_test/src/data/repositories/alias_repository.dart'
    as _i4;
import 'package:nubank_mobile_test/src/data/services/api/url_shortener_api.dart'
    as _i2;
import 'package:nubank_mobile_test/src/domain/dtos/alias_dto.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUrlShortenerApi_0 extends _i1.SmartFake
    implements _i2.UrlShortenerApi {
  _FakeUrlShortenerApi_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLog_1 extends _i1.SmartFake implements _i3.Log {
  _FakeLog_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AliasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAliasRepository extends _i1.Mock implements _i4.AliasRepository {
  MockAliasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UrlShortenerApi get urlShorApi =>
      (super.noSuchMethod(
            Invocation.getter(#urlShorApi),
            returnValue: _FakeUrlShortenerApi_0(
              this,
              Invocation.getter(#urlShorApi),
            ),
          )
          as _i2.UrlShortenerApi);

  @override
  _i3.Log get log =>
      (super.noSuchMethod(
            Invocation.getter(#log),
            returnValue: _FakeLog_1(this, Invocation.getter(#log)),
          )
          as _i3.Log);

  @override
  _i5.Future<_i6.AliasDto?> getUrl(String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#getUrl, [alias]),
            returnValue: _i5.Future<_i6.AliasDto?>.value(),
          )
          as _i5.Future<_i6.AliasDto?>);

  @override
  _i5.Future<_i6.AliasDto?> createAlias(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#createAlias, [url]),
            returnValue: _i5.Future<_i6.AliasDto?>.value(),
          )
          as _i5.Future<_i6.AliasDto?>);
}
